services:
  mysql:
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=serverdb'
      - 'MYSQL_PASSWORD=PNSJkxXvVNDAhePMuExTBuRR'
      - 'MYSQL_ROOT_PASSWORD=PNSJkxXvVNDAhePMuExTBuRR'
      - 'MYSQL_USER=servermanager'
      - 'TZ=Asia/Jakarta'
    volumes:
      - '$PWD/docker/server-db/conf.d":/etc/mysql/conf.d'
      - '$PWD/storage/docker/serverdb-data":/var/lib/mysql'

    ports:
      - '6603:3306'
    expose:
      - '6603'