services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: serverdb
      MYSQL_PASSWORD: PNSJkxXvVNDAhePMuExTBuRR
      MYSQL_ROOT_PASSWORD: PNSJkxXvVNDAhePMuExTBuRR
      MYSQL_USER: servermanager
      TZ: Asia/Jakarta
    volumes:
      - ./docker/server-db/conf.d:/etc/mysql/conf.d
      - ./storage/docker/serverdb-data:/var/lib/mysql
    ports:
      - "6603:3306"
    expose:
      - 6603